version: '3'

services:
  mysql:
    image: mysql
    command:
      - --innodb-use-native-aio=0
    container_name: dbAutomoveis
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=frez_automoveis
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306